create table if not exists public.rsvps (
  id bigint generated by default as identity primary key,
  event_slug text not null,
  event_title text not null,
  name text not null,
  email text not null,
  guests int not null default 1,
  note text,
  created_at timestamptz not null default now()
);

-- If you are using SUPABASE_ANON_KEY for inserts from /api/rsvp,
-- enable RLS and add an insert policy.
alter table public.rsvps enable row level security;

create policy if not exists "Allow public insert for RSVPs"
  on public.rsvps
  for insert
  to anon
  with check (true);
